---
grails:

  controllers:
    upload:
      maxFileSize: 314572800
      maxRequestSize: 314572800

  cors:
    enabled: true
  server:
    port: 8090
    contextPath: '/starter'
    use-forward-headers: true
    session:
      timeout: 7200

  profile: web

  codegen:
    defaultPackage: unify32

  spring:
    transactionManagement:
      proxies: false

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

  # Spring Actuator Endpoints are Disabled by Default
  # disable to avoid conflict UnableToRegisterMBeanException
  endpoints:
    enabled: false
  jmx:
    enabled: false
    unique-names: true


---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none

---
hibernate:
  c3p0.maxIdleTime: 18000
  c3p0.testConnectionOnCheckout: true
  hibernate.c3p0.timeout: 18000
  #---
  cache:
    use_query_cache: false
    use_second_level_cache: true
    provider_class: net.sf.ehcache.hibernate.EhCacheProvider
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  username: "root"
  password: "root"


environments:

  development:

    #logHibernateStats:
    #enabled: 'ALWAYS'
    # From ALWAYS, ALLOWED, NEVER

    grails:
      serverURL: http://localhost:8090/starter

    server:
      port: 8090
      contextPath: '/starter'
      session:
        timeout: 7200
    dataSource:
      #--------
      logSql: false
      formatSql: false
      #---------
      #dbCreate: create-drop
      #dbCreate: create
      dbCreate: update
      #dbCreate: create-drop
      username: "starter"
      password: "starter"
      dialect: unify32.MySQLUTF8InnoDBDialect
      url: jdbc:mysql://localhost:3306/starter?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      properties:
        dbProperties:
          autoReconnect: true
          connectTimeout: 15000
          socketTimeout: 120000

  test:
    dataSource:
      #--------
      logSql: true
      formatSql: false
      #---------
      dbCreate: create-drop
      #dbCreate: create
      #dbCreate: update
      #dbCreate: create-drop
      username: "starter"
      password: "starter"
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: unify32.MySQLUTF8InnoDBDialect
      url: jdbc:mysql://localhost:3306/starter?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      properties:
        dbProperties:
          autoReconnect: true
          connectTimeout: 15000
          socketTimeout: 120000


  production:
    grails:
      serverURL: "${SERVER_URL}"
    server:
      port: 8080
      contextPath: "${CONTEXT_PATH}"
      session:
        timeout: 86400
    dataSource:
      dbCreate: update
      url: "${DB_CONNECTION}"
      dialect: unify32.MySQLUTF8InnoDBDialect
      username: "${DB_USER}"
      password: "${DB_PASS}"
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 1800000
        minEvictableIdleTimeMillis: 1800000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
      dbProperties:
        autoReconnect: true
        connectTimeout: 15000
        socketTimeout: 120000




